# Generated by Django 5.1.1 on 2024-10-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('description_image', models.ImageField(upload_to='products/descriptions/')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount percentage', max_digits=5)),
                ('excat_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('discount_cut_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('product_type', models.CharField(help_text='Product type (e.g., storage, color, liters, etc.)', max_length=255)),
                ('product_capacity', models.CharField(help_text='Capacity or specifications (e.g., 512GB, Red, 1L)', max_length=50)),
                ('qrcode_image', models.ImageField(upload_to='products/qrcodes/')),
                ('payment_link', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=100)),
                ('road_name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
