# Generated by Django 5.1.1 on 2024-10-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_address_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='time',
        ),
    ]
